### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [MalloZup/fullrocketmetal#1]
Hi @MalloZup I am [Tobaloidee](https://steemit.com/@tobaloidee) a graphic artist and i would like to contribute by designing a logo for your new project. I just need your permission first before i start. Best regards!

**Comment by MalloZup** [comment]
Thx for your proposal! Sounds cool thx a lot, do you have already something in mind? ❤️❤️❤️

**Comment by Tobaloidee** [comment]
i will show you here when i finish my initial draft sir.. 👍

**Comment by Tobaloidee** [comment]
I hope you like it!
![FullRocketMetal Initial D-03](https://user-images.githubusercontent.com/36028424/55228747-e473c180-5255-11e9-854d-ecee5a05bbb8.png)

**Comment by MalloZup** [comment]
hi @Tobaloidee  looks great!.
The only one thing i was wondering if we could also infuse the  `design` of rocketchat, since this project will b with rocketchat (https://rocket.chat/)

i Dunno something with space or rockets.. :cupid:

**Comment by Tobaloidee** [comment]
actually the red color pixel was based from the rocketchat color scheme Sir. But i will think of a way to tweak it and infuse some rocketchat visibility there..will post it again after..

**Comment by MalloZup** [comment]
@Tobaloidee ok, cool thx! imho it would be super-fantastic with something which reminds the space or rocket.. but already now is awesome..! thx for your contribution @Tobaloidee :rocket:

**Comment by Tobaloidee** [comment]
second version
![rocketchatBOT-05](https://user-images.githubusercontent.com/36028424/55249473-1b160000-5287-11e9-96a8-c2a7a4d4f31c.png)

**Comment by MalloZup** [comment]
Thx  I think the 1st logo is more original. Yep I was wrong 😁 feel free to send a pr with 1st one thx lot

**Comment by Tobaloidee** [comment]
Hello @MalloZup  here's the PR #2 with the logo upload and readme update. I will make other file formats and share my drive link here for downloads. Again, thank you so much for accepting and allowing me to design a logo to your good project! Best regards! - [Tobaloidee](https://github.com/Tobaloidee) 💯

**Comment by MalloZup** [comment]
Thx à lot. I might create a Lib for the rocketchat I think we could reuse 2nd logo, I will ping you when time comes. Thx and enjoy

**Comment by MalloZup** [comment]
@Tobaloidee  if you have time, i'm doing another project `https://github.com/MalloZup/blacktango`.

Feel free to do whatever inspire you if you want tia

**Comment by MalloZup** [comment]
@Tobaloidee  for the 2nd logo, i think we can use it there: https://github.com/MalloZup/missile.

So basically this project will use the generic library from other project. 
I was thinking we should use the color from `clojure` instead of the rocketchat colors on the 2nd log for `missile` lib. 

https://clojure.org/

**Comment by Tobaloidee** [comment]
i'll make a PR and upload the 2nd logo there when i finished all the files @MalloZup .I am currently away from my pc now..I will work on it asap. 👍

**Comment by Tobaloidee** [comment]
Hi @MalloZup  I have finished the different file formats of your new FullRocketMetal logo..You can download it all [HERE](https://drive.google.com/drive/u/1/folders/1vL-rINhzYHyuFFSCDcW6IaVpX1t59uFA)

Thanks and best regards!
-Tobaloidee
